### ISSUE TITLE
css calc()

### ISSUE THREAD

**Issue by thegrince** [Chris2011/minifierbeans#16]
Hello,
Thank you for this great tool.
I am using v 2.2.1 in Netbeans 8.
It seems that css calc() spaces are removed, which breaks the instruction.
ex: calc(1vw + 10px) =>minify=> calc(1vw+10px)
Is there anything I can do to prevent that ?
Olivier

**Comment by Chris2011** [comment]
I think that should be fixed by the plugin or maybe a newer version of the dependencies that they need. Calc should be an exception for this.

**Comment by Chris2011** [comment]
But maybe you can check it again, because it was updated 3 months ago.

**Comment by answeb** [comment]
Hello, I think the problem is still here, in 2.2.1/Netbeans 8.2 :
Original : left: calc(100% + 7.3%);
Minified : left:calc(100%+7.3%)

**Comment by Chris2011** [comment]
It is still there and the problem is the YUI compressor: https://github.com/yui/yuicompressor/issues/268

**Comment by Chris2011** [comment]
So with the switch from YUICompressor to CSSNano using node and postcss + config, this is fixed in version 3.0.0.

Original File:
```css
body {
    margin: calc(1vw + 10px);
    left: calc(100% - -7.3%);
}
```

Minified File:
```css
body{margin:calc(1vw + 10px);left:107.3%}
```

Please give me some time (hopefully next week) to prepare the release of it. The UI changed and the implementation. But I think I'm on the right way of using node instead of not maintained Java libs.
